"""Mensagem da migração

Revision ID: 487b6cab5b8f
Revises: 38c4e85512a9
Create Date: 2025-01-08 14:05:47.270046

"""

# revision identifiers, used by Alembic.
revision = '487b6cab5b8f'
down_revision = '38c4e85512a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###